FROM debian:forky

# renovate: datasource=debian-14 depName=curl
ARG CURL_VERSION=8.18.0-2
# renovate: datasource=debian-14 depName=wget
ARG WGET_VERSION=1.21.3-1+deb12u1
# renovate: datasource=debian-14 depName=openssl
ARG OPENSSL_VERSION=3.5.4-1
# renovate: datasource=debian-14 depName=git
ARG GIT_VERSION=1:2.51.0-1

RUN apt-get update && \
    apt-get install -y \
      curl="${CURL_VERSION}" \
      wget="${WGET_VERSION}" \
      openssl="${OPENSSL_VERSION}" \
      git="${GIT_VERSION}" && \
    rm -rf /var/lib/apt/lists/*
