FROM debian:13@sha256:4ae67669760b807c19f23902a3fd7c121a6a70cf2ae709035674b23e712e4d62

# renovate: datasource=debian-13 depName=curl
ARG CURL_VERSION=8.14.1-1
# renovate: datasource=debian-13 depName=wget
ARG WGET_VERSION=1.21.3-1+deb12u1
# renovate: datasource=debian-13 depName=openssl
ARG OPENSSL_VERSION=3.5.1-1
# renovate: datasource=debian-13 depName=git
ARG GIT_VERSION=1:2.39.5-0+deb12u3

RUN apt-get update && \
    apt-get install -y \
      curl="${CURL_VERSION}" \
      wget="${WGET_VERSION}" \
      openssl="${OPENSSL_VERSION}" \
      git="${GIT_VERSION}" && \
    rm -rf /var/lib/apt/lists/*
