FROM ubuntu:24.04@sha256:db6914f1ac0c566f57857641e2214e3f3e453cb340cc2c890ed6c2b7b81b8a00

# renovate: datasource=ubuntu-2404 depName=curl
ARG CURL_VERSION=8.5.0-2ubuntu10.6
# renovate: datasource=ubuntu-2404 depName=wget
ARG WGET_VERSION=1.21.4-1ubuntu4
# renovate: datasource=ubuntu-2404 depName=openssl
ARG OPENSSL_VERSION=3.0.13-0ubuntu3.5
# renovate: datasource=ubuntu-2404 depName=git
ARG GIT_VERSION=1:2.43.0-1ubuntu7

RUN apt-get update && \
    apt-get install -y \
      curl="${CURL_VERSION}" \
      wget="${WGET_VERSION}" \
      openssl="${OPENSSL_VERSION}" \
      git="${GIT_VERSION}" && \
    rm -rf /var/lib/apt/lists/*
